ALTER TABLE BAND
ADD CONSTRAINT UQ_band_name UNIQUE(name);

ALTER TABLE ALBUM
ADD CONSTRAINT UQ_album_name UNIQUE(album_name);

ALTER TABLE ALBUM
ADD CONSTRAINT UQ_country UNIQUE(country);

ALTER TABLE GENRE
ADD CONSTRAINT UQ_genre_name UNIQUE(name);

ALTER TABLE ALBUM_GENRE
ADD CONSTRAINT UQ_album_id_genre_id UNIQUE(album_id, genre_id);
